=== marcellszabo921/FU7OMCWebXML/XMLTaskFU7OMC/DOMParseFU7OMC/XMLSchemaFU7OMC.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="korTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxExclusive value="100"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="szemelyTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Vegzettseg" type="xs:string" minOccurs="0"/>
            <xs:element name="Eletkor" type="korTipus"/>
        </xs:sequence>
        <xs:attribute name="Kod" type="xs:string" use="required"/>
    </xs:complexType>

    <xs:complexType name="CimTipus">
        <xs:sequence>
            <xs:element name="Varos" type="xs:string"/>
            <xs:element name="Utca" type="xs:string"/>
            <xs:element name="Hazszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MegrendeloTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"/>
            <xs:element name="Cim" type="CimTipus"/>
            <xs:element name="Telefonszam" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RendelesTipus">
        <xs:sequence>
            <xs:element name="Termek" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element name="Osszeg" type="xs:decimal"/>
            <xs:element name="Datum" type="xs:date"/>
        </xs:sequence>
    </xs:complexType>

    <xs:element name="Ipar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Gyar" minOccurs="1" maxOccurs="100">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nev" type="xs:string"/>
                            <xs:element name="Cim" type="CimTipus"/>
                            <xs:element name="Adoszam" type="xs:string"/>
                            <xs:element name="MuszakVezeto" type="szemelyTipus" minOccurs="1" maxOccurs="100"/>
                            <xs:element name="Szakmunkas" type="szemelyTipus" minOccurs="1" maxOccurs="100"/>
                            <xs:element name="Gyakornok" type="szemelyTipus" minOccurs="1" maxOccurs="100"/>
                            <xs:element name="Megrendelo" type="MegrendeloTipus" minOccurs="1" maxOccurs="100"/>
                            <xs:element name="Rendeles" type="RendelesTipus" minOccurs="1" maxOccurs="100"/>
                        </xs:sequence>
                        <xs:attribute name="Gyarkod" type="xs:string" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== marcellszabo921/FU7OMCWebXML/XMLTaskFU7OMC/DOMParseFU7OMC/XMLFU7OMC.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Ipar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaFU7OMC.xsd">
    <Gyar Gyarkod="A1">
        <Nev>AcélMűvek</Nev>
        <Cim>
            <Varos>Miskolc</Varos>
            <Utca>Szép lány</Utca>
            <Hazszam>54</Hazszam>
        </Cim>
        <Adoszam>111111111-1-11</Adoszam>

        <!-- Több műszakvezető -->
        <MuszakVezeto Kod="M1">
            <Nev>Trombitás Elemér</Nev>
            <Vegzettseg>Lakatos</Vegzettseg>
            <Eletkor>62</Eletkor>
        </MuszakVezeto>
        <MuszakVezeto Kod="M2">
            <Nev>Nagy Ferenc</Nev>
            <Vegzettseg>Gépész</Vegzettseg>
            <Eletkor>55</Eletkor>
        </MuszakVezeto>

        <!-- Több szakmunkás -->
        <Szakmunkas Kod="SZ1">
            <Nev>Szabó Gábor</Nev>
            <Vegzettseg>Kisegítő</Vegzettseg>
            <Eletkor>32</Eletkor>
        </Szakmunkas>
        <Szakmunkas Kod="SZ2">
            <Nev>Kovács László</Nev>
            <Vegzettseg>Villanyszerelő</Vegzettseg>
            <Eletkor>45</Eletkor>
        </Szakmunkas>

        <!-- Több gyakornok -->
        <Gyakornok Kod="Gyak1">
            <Nev>Illés Dániel</Nev>
            <Eletkor>20</Eletkor>
        </Gyakornok>
        <Gyakornok Kod="Gyak2">
            <Nev>Hegedűs Emese</Nev>
            <Eletkor>22</Eletkor>
        </Gyakornok>

        <!-- Több megrendelő -->
        <Megrendelo>
            <Nev>Máv Zrt.</Nev>
            <Cim>
                <Varos>Budapest</Varos>
                <Utca>Máv</Utca>
                <Hazszam>32</Hazszam>
            </Cim>
            <Telefonszam>+36 20 456 4353</Telefonszam>
        </Megrendelo>
        <Megrendelo>
            <Nev>Volánbusz Zrt.</Nev>
            <Cim>
                <Varos>Debrecen</Varos>
                <Utca>Nagyerdei körút</Utca>
                <Hazszam>5</Hazszam>
            </Cim>
            <Telefonszam>+36 30 123 4567</Telefonszam>
        </Megrendelo>

        <!-- Több termék a rendelésben -->
        <Rendeles>
            <Termek>Vasúti Sín</Termek>
            <Termek>Acél Lemez</Termek>
            <Termek>Csavar</Termek>
            <Osszeg>12345654.00</Osszeg>
            <Datum>2024-03-21</Datum>
        </Rendeles>
        <Rendeles>
            <Termek>Betongerenda</Termek>
            <Termek>Acélcső</Termek>
            <Osszeg>5789000.00</Osszeg>
            <Datum>2024-04-10</Datum>
        </Rendeles>
    </Gyar>
</Ipar>
