=== marcellszabo921/FU7OMCWebXML/XMLTaskFU7OMC/DOMParseFU7OMC/src/resources/XMLSchemaFU7OMC.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="korTipus">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"></xs:minInclusive>
            <xs:maxExclusive value="100"></xs:maxExclusive>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="szemelyzet">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"></xs:element>
            <xs:element name="Vegzettseg" type="xs:string"></xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="MuszakVezetoTipus">
        <xs:complexContent>
            <xs:extension base="szemelyzet">
                <xs:sequence>
                    <xs:element name="Eletkor" type="korTipus"></xs:element>
                </xs:sequence>
                <xs:attribute name="M_kod" type="xs:string" use="required"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="SzakmunkasTipus">
        <xs:complexContent>
            <xs:extension base="szemelyzet">
                <xs:sequence>
                    <xs:element name="Eletkor" type="korTipus"></xs:element>
                </xs:sequence>
                <xs:attribute name="Sz_kod" type="xs:string" use="required"></xs:attribute>
            </xs:extension>
        </xs:complexContent>
    </xs:complexType>

    <xs:complexType name="GyakornokTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"></xs:element>
            <xs:element name="Eletkor" type="korTipus"></xs:element>
            <xs:element name="Gyakorlat">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="Kezdete" type="xs:string"></xs:element>
                        <xs:element name="Idotartam" type="xs:string"></xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
        <xs:attribute name="Gy_kod" type="xs:string" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="MegrendeloTipus">
        <xs:sequence>
            <xs:element name="Nev" type="xs:string"></xs:element>
            <xs:element name="Telefonszam" type="xs:string"></xs:element>
            <xs:element name="Cim" type="CimTipus"></xs:element>
        </xs:sequence>
        <xs:attribute name="Mkod" use="required"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="RendelesTipus">
        <xs:sequence>
            <xs:element name="Osszeg" type="xs:integer"></xs:element>
            <xs:element name="Termek" type="xs:string" minOccurs="1" maxOccurs="unbounded"></xs:element>
            <xs:element name="Datum" type="xs:string"></xs:element>
        </xs:sequence>
        <xs:attribute name="Rkod" type="xs:string"></xs:attribute>
        <xs:attribute name="GyarMR" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:complexType name="CimTipus">
        <xs:sequence>
            <xs:element name="Varos" type="xs:string"></xs:element>
            <xs:element name="Utca" type="xs:string"></xs:element>
            <xs:element name="Hazszam" type="xs:string"></xs:element>
        </xs:sequence>
        <xs:attribute name="Rkod" type="xs:string"></xs:attribute>
    </xs:complexType>

    <xs:element name="Ipar">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Gyar">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="Nev" type="xs:string"></xs:element>
                            <xs:element name="Cim" type="CimTipus"></xs:element>
                            <xs:element name="Adoszam" type="xs:integer"></xs:element>
                            <xs:element name="MuszakVezeto" type="MuszakVezetoTipus"></xs:element>
                            <xs:element name="Szakmunkas" type="SzakmunkasTipus"></xs:element>
                            <xs:element name="Gyakornok" type="GyakornokTipus"></xs:element>
                            <xs:element name="Megrendelo" type="MegrendeloTipus"></xs:element>
                            <xs:element name="Rendeles" type="RendelesTipus"></xs:element>
                        </xs:sequence>
                        <xs:attribute name="Gyarkod" type="xs:string"></xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== marcellszabo921/FU7OMCWebXML/XMLTaskFU7OMC/DOMParseFU7OMC/src/resources/XMLFU7OMC1.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Ipar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaFU7OMC.xsd">
    <Gyar Gyarkod="A1">
        <Nev>SínCsináló Kft.</Nev> 
        <Cim>
            <Varos>Miskolc,</Varos>
            <Utca>Szép lány</Utca>
            <Hazszam>54</Hazszam>
        </Cim>
        <Adoszam>ABCD1234</Adoszam>
        <MuszakVezeto M_kod="M1">
            <Nev>Trombitás Elemér</Nev> 
            <Eletkor>62</Eletkor>
            <Vegzettseg>Lakatos</Vegzettseg>
        </MuszakVezeto>
        <Szakmunkas Sz_kod="SZ1">
            <Nev>Szabó Gábor</Nev> 
            <Eletkor>32</Eletkor>
            <Vegzettseg>Kisegítő</Vegzettseg>
        </Szakmunkas>
        <Szakmunkas Sz_kod="SZ2">
            <Nev>Lakatos Attila</Nev> 
            <Eletkor>48</Eletkor>
            <Vegzettseg>Hegesztő</Vegzettseg>
        </Szakmunkas>
        <Gyakornok Gy_kod="Gyak1">
            <Nev>Illés Dániel</Nev> 
            <Gyakorlat>
                <Kezdete>2024.02.14</Kezdete>
                <Idotartam>8 hét</Idotartam>
            </Gyakorlat>
            <Eletkor>20</Eletkor>
        </Gyakornok>
        <Megrendelo Mkod="M1">
            <Nev>Máv Zrt.</Nev> 
            <Cim>
                <Varos>Budapest</Varos>
                <Utca>Máv</Utca>
                <Hazszam>32</Hazszam>
            </Cim>
            <Telefonszam>+36 20 456 4353</Telefonszam>
        </Megrendelo>
        <Rendeles GyarMR="GYR1" Rkod="R1">
            <Termek>Vasúti Sín</Termek>
            <Osszeg>12,345,654 Ft</Osszeg>
            <Datum>2024.03.21.</Datum>
        </Rendeles>
    </Gyar>
    <Gyar Gyarkod="A2">
        <Nev>Lakatos Négyes Kft.</Nev> 
        <Cim>
            <Varos>Szeged,</Varos>
            <Utca>Alma</Utca>
            <Hazszam>122</Hazszam>
        </Cim>
        <Adoszam>ADEFG231</Adoszam>
        <MuszakVezeto M_kod="M2">
            <Nev>Lézer Géza</Nev> 
            <Eletkor>56</Eletkor>
            <Vegzettseg>Virágkötő</Vegzettseg>
        </MuszakVezeto>
        <Szakmunkas Sz_kod="SZ3">
            <Nev>Vad Levente</Nev> 
            <Eletkor>23</Eletkor>
            <Vegzettseg>Lakatos</Vegzettseg>
        </Szakmunkas>
        <Szakmunkas Sz_kod="SZ4">
            <Nev>Lázár Ferenc</Nev> 
            <Eletkor>28</Eletkor>
            <Vegzettseg>Lakatos</Vegzettseg>
        </Szakmunkas>
        <Gyakornok Gy_kod="Gyak2">
            <Nev>Gál Ágoston</Nev> 
            <Gyakorlat>
                <Kezdete>2024.08.04</Kezdete>
                <Idotartam>4 hét</Idotartam>
            </Gyakorlat>
            <Eletkor>23</Eletkor>
        </Gyakornok>
        <Megrendelo Mkod="M2">
            <Nev>Szabó Ábel</Nev> 
            <Cim>
                <Varos>Szeged</Varos>
                <Utca>Pillangó</Utca>
                <Hazszam>16</Hazszam>
            </Cim>
            <Telefonszam>+36 30 765 9812</Telefonszam>
        </Megrendelo>
        <Rendeles GyarMR="GYR2" Rkod="R2">
            <Termek>XXL Lakat</Termek>
            <Osszeg>378.990 Ft</Osszeg>
            <Datum>2024.07.01.</Datum>
        </Rendeles>
    </Gyar>
    <Gyar Gyarkod="A1">
        <Nev>SínCsináló Kft.</Nev> 
        <Cim>
            <Varos>Miskolc,</Varos>
            <Utca>Szép lány</Utca>
            <Hazszam>54</Hazszam>
        </Cim>
        <Adoszam>ABCD1234</Adoszam>
        <MuszakVezeto M_kod="M1">
            <Nev>Trombitás Elemér</Nev> 
            <Eletkor>62</Eletkor>
            <Vegzettseg>Lakatos</Vegzettseg>
        </MuszakVezeto>
        <Szakmunkas Sz_kod="SZ1">
            <Nev>Szabó Gábor</Nev> 
            <Eletkor>32</Eletkor>
            <Vegzettseg>Kisegítő</Vegzettseg>
        </Szakmunkas>
        <Szakmunkas Sz_kod="SZ2">
            <Nev>Lakatos Attila</Nev> 
            <Eletkor>48</Eletkor>
            <Vegzettseg>Hegesztő</Vegzettseg>
        </Szakmunkas>
        <Gyakornok Gy_kod="Gyak1">
            <Nev>Illés Dániel</Nev> 
            <Gyakorlat>
                <Kezdete>2024.02.14</Kezdete>
                <Idotartam>8 hét</Idotartam>
            </Gyakorlat>
            <Eletkor>20</Eletkor>
        </Gyakornok>
        <Megrendelo Mkod="M1">
            <Nev>Máv Zrt.</Nev> 
            <Cim>
                <Varos>Budapest</Varos>
                <Utca>Máv</Utca>
                <Hazszam>32</Hazszam>
            </Cim>
            <Telefonszam>+36 20 456 4353</Telefonszam>
        </Megrendelo>
        <Rendeles GyarMR="GYR1" Rkod="R1">
            <Termek>Vasúti Sín</Termek>
            <Osszeg>12,345,654 Ft</Osszeg>
            <Datum>2024.03.21.</Datum>
        </Rendeles>
    </Gyar>
    <Gyar Gyarkod="A3">
        <Nev>Szabó Cipő és Társa</Nev> 
        <Cim>
            <Varos>Kecskemét,</Varos>
            <Utca>Barack</Utca>
            <Hazszam>43</Hazszam>
        </Cim>
        <Adoszam>VCVES421</Adoszam>
        <MuszakVezeto M_kod="M3">
            <Nev>Sándor Barnabás</Nev> 
            <Eletkor>42</Eletkor>
            <Vegzettseg>Cipész mester</Vegzettseg>
        </MuszakVezeto>
        <Szakmunkas Sz_kod="SZ5">
            <Nev>Pál Kata</Nev> 
            <Eletkor>29</Eletkor>
            <Vegzettseg>Cipész</Vegzettseg>
        </Szakmunkas>
        <Szakmunkas Sz_kod="SZ6">
            <Nev>Albán Jóna</Nev> 
            <Eletkor>37</Eletkor>
            <Vegzettseg>Cipész</Vegzettseg>
        </Szakmunkas>
        <Gyakornok Gy_kod="Gyak3">
            <Nev>Fazekas Gergő</Nev> 
            <Gyakorlat>
                <Kezdete>2024.11.04</Kezdete>
                <Idotartam>6 hét</Idotartam>
            </Gyakorlat>
            <Eletkor>24</Eletkor>
        </Gyakornok>
        <Megrendelo Mkod="M3">
            <Nev>Álmos Elemér</Nev> 
            <Cim>
                <Varos>Miskolc</Varos>
                <Utca>Erkel Ferenc</Utca>
                <Hazszam>37</Hazszam>
            </Cim>
            <Telefonszam>+36 70 685 0832</Telefonszam>
        </Megrendelo>
        <Rendeles GyarMR="GYR3" Rkod="R3">
            <Termek>46-os Bőr bakkancs</Termek>
            <Osszeg>57.990 Ft</Osszeg>
            <Datum>2024.10.29.</Datum>
        </Rendeles>
    </Gyar>
</Ipar>

=== marcellszabo921/FU7OMCWebXML/XMLTaskFU7OMC/DOMParseFU7OMC/src/resources/XMLFU7OMC.xml
<?xml version="1.0" encoding="UTF-8"?>
<Ipar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="XMLSchemaFU7OMC.xsd">
    <Gyar Gyarkod="A1">
        <Nev></Nev> 
        <Cim>
            <Varos></Varos>
            <Utca></Utca>
            <Hazszam></Hazszam>
        </Cim>
        <Adoszam></Adoszam>
        <Muszak_Vezeto M_kod="B1">
            <Nev></Nev> 
            <Eletkor></Eletkor>
            <Vegzettseg></Vegzettseg>
        </Muszak_Vezeto>
        <Szakmunkas Sz_kod="C1">
            <Nev></Nev> 
            <Eletkor></Eletkor>
            <Vegzettseg></Vegzettseg>
        </Szakmunkas>
        <Gyakornok Gy_kod="D1">
            <Nev></Nev> 
            <Gyakorlat>
                <Kezdete></Kezdete>
                <Idotartam></Idotartam>
            </Gyakorlat>
            <Eletkor></Eletkor>
        </Gyakornok>
        <Megrendelo Mkod="E1">
            <Nev></Nev> 
            <Cim>
                <Varos></Varos>
                <Utca></Utca>
                <Hazszam></Hazszam>
            </Cim>
            <Telefonszam></Telefonszam>
        </Megrendelo>
        <Rendeles Rkod="F1" GyarMR="G1">
            <Termek></Termek>
            <Osszeg></Osszeg>
            <Datum></Datum>
        </Rendeles>
    </Gyar>
</Ipar>

=== marcellszabo921/FU7OMCWebXML/XMLTaskFU7OMC/DOMParseFU7OMC/src/resources/XML1FU7OMC.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><Ipar xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="XMLSchemaFU7OMC.xsd">
    <Gyar Gyarkod="A1">
        <Nev/> 
        <Cim>
            <Varos/>
            <Utca/>
            <Hazszam/>
        </Cim>
        <Adoszam/>
        <Muszak_Vezeto M_kod="B1">
            <Nev/> 
            <Eletkor/>
            <Vegzettseg/>
        </Muszak_Vezeto>
        <Szakmunkas Sz_kod="C1">
            <Nev/> 
            <Eletkor/>
            <Vegzettseg/>
        </Szakmunkas>
        <Gyakornok Gy_kod="D1">
            <Nev/> 
            <Gyakorlat>
                <Kezdete/>
                <Idotartam/>
            </Gyakorlat>
            <Eletkor/>
        </Gyakornok>
        <Megrendelo Mkod="E1">
            <Nev/> 
            <Cim>
                <Varos/>
                <Utca/>
                <Hazszam/>
            </Cim>
            <Telefonszam/>
        </Megrendelo>
        <Rendeles GyarMR="G1" Rkod="F1">
            <Termek/>
            <Osszeg/>
            <Datum/>
        </Rendeles>
    </Gyar>
</Ipar>
